version: "3.9"

services:
  go-api:
    container_name: go-app
    image: go-rest-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - my_db
  my_db:
    container_name: my_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}